# Generated by Django 3.2.19 on 2025-05-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ywsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shavasana_acting',
            field=models.IntegerField(choices=[(0, 'Depends on settings'), (1, 'Acting always'), (2, 'Never acting')], default=0),
        ),
    ]
