# Generated by Django 3.2.19 on 2025-05-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ywsapp', '0002_user_shavasana_acting'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='metronome',
            field=models.IntegerField(choices=[(0, 'Full'), (1, 'Bells only'), (2, 'No metronome sound')], default=0),
        ),
    ]
