# Generated by Django 3.2.19 on 2024-02-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ywsapp', '0002_userworkoutprops'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kegel_timer',
            field=models.BooleanField(default=False),
        ),
    ]
